version: '3.7'

services:
    riaclo_v2_host_db:
        container_name: 'db_riaclo_v2'
        image: 'postgres:14-alpine'
        restart: always
        env_file:
            - ./.env
        ports:
            - '5435:5432'
        volumes:
            - ./database/dbriaclov2develop:/var/lib/postgresql/data/

    riaclo_v2_api:
        container_name: 'riaclo_v2_api'
        build: .
        restart: always
        volumes:
            - .:/app/
            - /app/node_modules
        entrypoint: /bin/sh './scripts/be-node-dev.sh'
        env_file:
            - ./.env
        ports:
            - '4500:4500'
        depends_on:
            - riaclo_v2_host_db
        links:
            - riaclo_v2_host_db